### ISSUE TITLE
Update Angular Version

### ISSUE THREAD

**Issue by constantlb** [algolia/doc-code-samples#155]
Hey,

Will be so cool if you can update Angular version from 6 to 9 of your Angular InstantSearch Exemple :)

https://github.com/algolia/doc-code-samples/blob/master/Angular%20InstantSearch/places/package.json

**Comment by Haroenv** [comment]
sorry, angular InstantSearch isn't compatible with angular version 9 at this point yet, as tracked in https://github.com/algolia/angular-instantsearch/issues/713
