### ISSUE TITLE
Vue - Property or method "state" is not defined

### ISSUE THREAD

**Issue by JacquesViviarto** [algolia/doc-code-samples#234]
Hello,

I copy your code to create a map widget
https://github.com/algolia/doc-code-samples/blob/master/Vue%20InstantSearch/geo-search/src/components/Map.vue

And got
`Property or method "state" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.`

**Version**
 "vue": "^2.6.11",
"vue-instantsearch": "^3.4.2"

Thanks for your help,

**Comment by Haroenv** [comment]
Do you have a sandbox with this? the state variable gets defined in createWidgetMixin. I see no warning when running this code here: https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/Vue%20InstantSearch/geo-search

**Comment by JacquesViviarto** [comment]
I refresh my project from scratch with your example and its work. Sorry for this thread and thanks for your reply.

**Comment by Haroenv** [comment]
No worries, possibly you forgot to save when you added createWidgetMixin? Have a nice day and enjoy using Vue InstantSearch!
