### ISSUE TITLE
Angular samples don't use instantsearch.css styles directly

### ISSUE THREAD

**Issue by tkrugg** [algolia/doc-code-samples#41]
This makes them inconsistent with the rest of our samples
https://github.com/algolia/doc-code-samples/blob/master/Angular%20InstantSearch/getting-started/angular.json#L26

- [ ] Fixing this issue in create-instantsearch-app. https://github.com/algolia/create-instantsearch-app/pull/347
- [ ] release create-instantsearch-app
- [ ] update samples

**Comment by Haroenv** [comment]
we should probably remove the bundle alltogether

**Comment by tkrugg** [comment]
Agree, 
but that would be a breaking change.
I think it should be done as part of making instantsearch.css a peerDependency of angular-instantsearch.

Btw, I see Vue IS has 
- instantsearch.js as a [dependency](https://github.com/algolia/vue-instantsearch/blob/v2/package.json#L49)
- instantsearch.css as a [devDependency](https://github.com/algolia/vue-instantsearch/blob/v2/package.json#L72)

I forgot what was the plan: make them both peer dependencies?

**Comment by Haroenv** [comment]
InstantSearch.js as a dependency or peerDependency (I'm not convinced of either, both can go bad)

InstantSearch.css as no dependency or as an optionalDependency

**Comment by tkrugg** [comment]
I think Instantsearch.js as a dependency is better. To me the only libs that belong to it peer dependencies are those that might be required by other libs the user might be using, typically to have a single copy of it (eg. lodash, react).  It's unlikely with Instantsearch.js. WDYT?

I might be missing something but to me `optionalDependencies` are for system specific dependencies and doesn't apply to instantsearch.css

**Comment by Haroenv** [comment]
InstantSearch.css isn't required, so it isn't a peerDependency. It's either nothing at all, or an optional one. 

There's still use cases where something can be imported from InstantSearch.js directly (router, connectors e.g.), but in that case we can just assume that they know too make sure it's the same version

**Comment by Haroenv** [comment]
the samples use InstantSearch.css now as far as I can tell
