### ISSUE TITLE
Facet dropdown demo fails with instantsearch.js versions > 4.28.0

### ISSUE THREAD

**Issue by chuckmeyer** [algolia/doc-code-samples#422]
Due to panel rendering changes made in instantsearch.js v4.29.0 (https://github.com/algolia/instantsearch.js/pull/4845), dropdown.js can no longer retrieve `.ais-Panel-header` on init for the refinementList dropdown demo.

`        const headerElem = rootElem.querySelector('.ais-Panel-header');`

The issue was identified in this Discourse post:
https://discourse.algolia.com/t/erros-using-dropdown-js-withrefinementlists/16600/4

Error is as follows:

```
TypeError

Cannot read properties of null (reading 'querySelector')

Object.init

/src/Dropdown.js:93:36
  90 | const rootElem = document
  91 |   .querySelector(widgetParams.container)
  92 |   .querySelector('.ais-Panel');
> 93 | const headerElem = rootElem.querySelector('.ais-Panel-header');
     |                            ^
  94 | const closeButtonElem = rootElem.querySelector(
  95 |   '.' + CLASS_CLOSE_BUTTON
  96 | );
```

**Comment by stephanemartinw** [comment]
Hi, 

I've just tried out the latest version of instant-search js (4.49.2) and the issue is still present. 
A second one is displayed, one a search is triggered:  

renderTemplate.ts:65 Uncaught (in promise) Error: Template must be 'string' or 'function', was 'undefined' (key: item)
    at ea (renderTemplate.ts:65:11)
    at t.value (Template.tsx:62:21)
    at ar (preact.module.js:1:5807)
    at Xn (preact.module.js:1:2137)
    at preact.module.js:1:7356
    at ar (preact.module.js:1:6320)
    at Xn (preact.module.js:1:2137)
    at ar (preact.module.js:1:6138)
    at Xn (preact.module.js:1:2137)
    at preact.module.js:1:7356
    
    So, using dropdown facets is impossible with latest instant search. 
    Can you help ? We are facing here a problem that blocks the developement of our application. 
    
    Thank you for your help.
