### ISSUE TITLE
Search for ID

### ISSUE THREAD

**Issue by sonalmahajan01** [algolia/doc-code-samples#66]
With no URL routing searching for an id works like :
<url>q=&idx=<index_name>&p=0&dFR[objectID][0]=387&dFR[objectID][1]=386
The above logic doesn't work for this?

**Comment by Haroenv** [comment]
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js). Thanks!

**Comment by samouss** [comment]
I'm closing this issue because it's inactive since a while. Feel free to open a new one!
